<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>CWatch.Cleanup</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CWatch.Core\CWatch.Core.csproj" />
    <ProjectReference Include="..\CWatch.Infrastructure\CWatch.Infrastructure.csproj" />
  </ItemGroup>

</Project>
