using CWatch.Core.Enums;
using CWatch.Core.Interfaces;
using CWatch.Core.Models;
using CWatch.Core.Safety;
using CWatch.Infrastructure.WindowsApi;

namespace CWatch.Cleanup.Providers;

public sealed class WindowsTempCleanupProvider : ICleanupProvider
{
    public string ProviderId => "windows_temp";
    public string DisplayName => "Windows & User Temporary Files";
    public string CategoryName => "Temporary Files";
    public bool IsAdvanced => false;

    public async Task<List<CleanupCandidate>> ScanCandidatesAsync(CancellationToken cancellationToken = default)
    {
        return await Task.Run(() =>
        {
            var candidates = new List<CleanupCandidate>();

            // 1. User Temp
            string userTemp = Path.GetTempPath();
            if (Directory.Exists(userTemp) && PathSafetyValidator.IsSafeForCleanup(userTemp))
            {
                long size = CalculateDirectorySize(userTemp);
                if (size > 0)
                {
                    candidates.Add(new CleanupCandidate
                    {
                        ProviderId = ProviderId,
                        Title = "User Temporary Files",
                        Description = "Temporary working files generated by user applications and installers.",
                        Path = userTemp,
                        SizeBytes = size,
                        Safety = SafetyLevel.Safe,
                        Reason = "Applications create temporary files during operation and installation that are no longer needed.",
                        WhatWillHappen = "Deletes non-locked temporary files. Running apps will recreate active files as needed.",
                        WillRegenerate = true,
                        Category = StorageCategoryType.TemporaryFiles
                    });
                }
            }

            // 2. Windows Temp
            string winTemp = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Windows), "Temp");
            if (Directory.Exists(winTemp) && PathSafetyValidator.IsSafeForCleanup(winTemp))
            {
                long size = CalculateDirectorySize(winTemp);
                if (size > 0)
                {
                    candidates.Add(new CleanupCandidate
                    {
                        ProviderId = ProviderId,
                        Title = "Windows System Temp Files",
                        Description = "System-level temporary files generated by Windows update, drivers, and background services.",
                        Path = winTemp,
                        SizeBytes = size,
                        Safety = SafetyLevel.Safe,
                        Reason = "System services leave behind installer and diagnostic logs in the Windows Temp directory.",
                        WhatWillHappen = "Deletes unlocked system temp files without affecting running services.",
                        WillRegenerate = true,
                        RequiresElevation = true,
                        Category = StorageCategoryType.TemporaryFiles
                    });
                }
            }

            return candidates;
        }, cancellationToken);
    }

    public async Task<CleanupResult> ExecuteCleanupAsync(
        IReadOnlyList<CleanupCandidate> candidates,
        IProgress<string>? progress = null,
        CancellationToken cancellationToken = default)
    {
        return await Task.Run(() =>
        {
            var result = new CleanupResult();
            var sw = System.Diagnostics.Stopwatch.StartNew();

            var enumOptions = new EnumerationOptions
            {
                AttributesToSkip = FileAttributes.ReparsePoint,
                IgnoreInaccessible = true,
                RecurseSubdirectories = true
            };

            foreach (var cand in candidates)
            {
                cancellationToken.ThrowIfCancellationRequested();

                if (!PathSafetyValidator.IsSafeForCleanup(cand.Path))
                {
                    result.ErrorMessages.Add($"Security guard blocked unsafe deletion path: {cand.Path}");
                    continue;
                }

                progress?.Report($"Cleaning {cand.Title}...");

                if (Directory.Exists(cand.Path))
                {
                    var di = new DirectoryInfo(cand.Path);

                    // Safely enumerate files skipping symlinks/junctions
                    foreach (var file in di.EnumerateFiles("*", enumOptions))
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                        try
                        {
                            long len = file.Length;
                            file.Delete();
                            result.BytesCleaned += len;
                            result.ItemsCleanedCount++;
                        }
                        catch (Exception ex)
                        {
                            result.FailedItemsCount++;
                            result.ErrorMessages.Add($"Could not delete {file.Name}: {ex.Message}");
                        }
                    }

                    // Try removing empty subfolders without traversing junction points
                    try
                    {
                        var dirEnumOptions = new EnumerationOptions
                        {
                            AttributesToSkip = FileAttributes.ReparsePoint,
                            IgnoreInaccessible = true,
                            RecurseSubdirectories = false
                        };

                        foreach (var sub in di.EnumerateDirectories("*", dirEnumOptions))
                        {
                            try
                            {
                                if ((sub.Attributes & FileAttributes.ReparsePoint) == 0)
                                {
                                    sub.Delete(true);
                                }
                            }
                            catch { }
                        }
                    }
                    catch { }
                }
            }

            sw.Stop();
            result.Duration = sw.Elapsed;
            return result;
        }, cancellationToken);
    }

    private static long CalculateDirectorySize(string path)
    {
        try
        {
            var di = new DirectoryInfo(path);
            var opt = new EnumerationOptions { IgnoreInaccessible = true, RecurseSubdirectories = true, AttributesToSkip = FileAttributes.ReparsePoint };
            return di.EnumerateFiles("*", opt).Sum(f => f.Length);
        }
        catch { return 0; }
    }
}
